name: Deploy Next.js site to Ironweb-Research's GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout _component folder
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src/app/_components
        # - name: Move blog post to correct level
        #   id: move_blog_post
      - name: Checkout receiving repo folder
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUSH_COMPONENTS_TOKEN }}
          path: temp_components
          repository: ironweb-research/we_are
          sparse-checkout: |
            src/app/_components

      #   run: |
      #     mv ./_posts/_posts/*.md _posts
      #     rm ./_posts/README.md
      #     find ./_posts -mindepth 1 -depth -type d ! -name "*.md" -exec rm -r {} +
      - name: Verify PWD 
        id: present-working-directory
        run: |
          echo "Present working directory---->: $(pwd)"
          echo "Advance check on all contents, incl hidden, are loaded onto present working directory"
          ls -lha
          echo "Advance check on workflow loaded onto ./temp_components"
          ls -lha ./temp_components
#          echo "Advance check on blog post loaded onto ./_posts"
#          ls -lha ./_posts
